# Generated by Django 4.1.2 on 2023-01-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trackermodel_textcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='imglastupdated',
            field=models.BigIntegerField(null=True),
        ),
    ]
